Repository geosolutions-it/MapStore2-C028, pull requests merged in 2020-05, with the labels that each got.

#104 86: exclude spring dependencies from print plugin
  web/pom.xml
Labels: Priority: Medium, Project: C028, bug

#105 87: Raise the apache.cxf log level to ERROR
  web/src/main/webapp/WEB-INF/classes/log4j.properties
Labels: Priority: Medium, Project: C028, enhancement

#112 89: old localization logic removed
  js/appConfig.js
  js/components/RecordItem.jsx
  js/embedded.jsx
  js/epics/__tests__/locale-test.js
  js/epics/layers.js
  js/epics/locale.js
  js/plugins.js
  js/plugins/MetadataExplorer.jsx
  js/utils/ProjectUtils.js
  js/utils/test/ProjectUtils-test.js
Labels: Project: C028

#130 add symbols, update local config
  assets/symbols/map-pin-marked.svg
  assets/symbols/symbolMissing.svg
  assets/symbols/symbols.json
  assets/symbols/triangle.svg
  localConfig.json
Labels: Priority: High, Project: C028, bug

#133 Worked on various issues
  assets/css/maps.css
  js/plugins/HomeDescription.jsx
  localConfig.json
  new.json
  webpack.config.js
Labels: Environment, Priority: High, Project: C028, bug, enhancement
